[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = [
    "geopandas>=1.0.1",
    "matplotlib>=3.10.1",
    "rasterio>=1.4.3",
    "rioxarray>=0.18.2",
    "scikit-learn>=1.6.1",
]
description = "Assorted tools for processing and visualizing hazardous algae blooms"
name = "smart_hab"
readme = "readme.md"
requires-python = ">=3.12"
version = "0.0.1"

[project.scripts]
about = "smart_hab.cli:about"
clip = "smart_hab.cli:clip"
convert_shape = "smart_hab.cli:convert_shape"
kmeans_fit = "smart_hab.cli:kmeans_fit"
kmeans_classify = "smart_hab.cli:kmeans_classify"
mask = "smart_hab.cli:mask"
means = "smart_hab.cli:means"
norm_diff = "smart_hab.cli:norm_diff"
plot = "smart_hab.cli:plot"
select_bands = "smart_hab.cli:select_bands"

[tool.hatch.build.targets.wheel]
packages = ["src/smart_hab"]
