#!/usr/bin/env bash

# usage: kmeans <workspace_dir> <config_file>

set -o pipefail

# global vars
config=""
workspace=""

# config vars
vars=(workspace centers_file centroids n_times seed files_fit files_classify)
centers_file=""
centroids=""
n_times=""
seed=""
files_fit=""
files_classify=""

function main {
	# parse subcommand
	local subcommand=""
	if [ "$#" -gt 0 ]; then
		subcommand="$1"
		shift
	fi

	# run subcommand
	case "$subcommand" in
		"config") subcommand_config "$@" ;;
		"run") subcommand_run "$@" ;;
		*)
			echo "Usage: kmeans config <config_file> <workspace_dir>"
			echo "       kmeans run    <config_file>"
			exit 1
			;;
	esac
}

function validate_config {
	local errors=()
	for var in "${vars[@]}"; do
		[ "${!var}" = "" ] && errors+=("$var is required")
	done
	if [ "${#errors[@]}" -gt 0 ]; then
		echo "# ✘ Invalid config file \"$config\"" |
			gum format
		for error in "${errors[@]}"; do
			echo "  - $error" |
				gum format
		done
		exit 1
	fi
}

function subcommand_config {
	# local vars
	local action=""

	# parse arguments
	case "$#" in

		# create new configuration file
		2)
			action="Choose"
			config="$1"
			workspace="$2"
			[ -f "$config" ] && source "$config" && validate_config
			# invariant: matching workspace in config and argument
			if [ "$2" != "" ] && [ "$workspace" != "$2" ]; then
				echo "# ✘ Config mismatch: \"$config\" is already configured for workspace \"$workspace\"" |
					gum format
				if ! gum confirm "Are you sure you want to overwrite \"$config\"?" --negative="Cancel"; then
					echo "# ✘ Aborted." |
						gum format
					exit 1
				fi
			fi
			;;

		# edit existing configuration file
		1)
			if [ ! -f "$1" ]; then
				echo "Usage: kmeans config <config_file> <workspace_dir>"
				echo "# ✘ Config file \"$1\" not found, aborting." |
					gum format
				exit 1
			fi
			action="Edit"
			config="$1"
			source "$config" && validate_config
			;;

		# invalid usage
		*)
			echo "Usage: kmeans config <config_file> <workspace_dir>"
			exit 1
			;;
	esac

	# ensure workspace is present
	if [ ! -d "$workspace" ]; then
		echo "# ✘ Workspace directory \"$workspace\" not found, aborting." |
			gum format
		exit 1
	fi

	local files_available=$(
		find "$workspace" \
			\( -type l -o -type f \) |
			sed "s:^$workspace/::" |
			sort
	)

	if [ "$files_available" = "" ]; then
		echo "# ✘ No files found in workspace \"$workspace\", aborting." |
			gum format
		exit 1
	fi

	centers_file=$(
		gum input \
			--header="[1/6] $action centers file... \"$centers_file\"" \
			--prompt="Centers file:" \
			--placeholder="centers.txt" \
			--value="$centers_file"
	)

	if [ "$centers_file" = "" ]; then
		centers_file="centers.txt"
	fi

	centroids=$(
		gum input \
			--header="[2/6] $action number of clusters... $centroids" \
			--prompt="Centroids:" \
			--placeholder="6" \
			--value="$centroids"
	)

	if ! [[ "$centroids" =~ ^[0-9]+$ ]]; then
		centroids=6
	fi

	n_times=$(
		gum input \
			--header="[3/6] $action number of iterations... $n_times" \
			--prompt="Iterations:" \
			--placeholder="10" \
			--value="$n_times"
	)

	if ! [[ "$n_times" =~ ^[0-9]+$ ]]; then
		n_times=10
	fi

	seed=$(
		gum input \
			--header="[4/6] $action random seed... $seed" \
			--prompt="Seed:" \
			--placeholder="42" \
			--value="$seed"
	)

	if ! [[ "$seed" =~ ^[0-9]+$ ]]; then
		seed=42
	fi

	files_fit=$(
		echo "$files_available" |
			sort |
			gum filter \
				--header="[5/6] $action fit rasters..." \
				--indicator=">" \
				--no-fuzzy \
				--no-fuzzy-sort \
				--no-limit \
				--prompt="" \
				--selected="$(echo -n "$files_fit" | tr "\n" ",")" \
				--selected-prefix=" ◼︎ " \
				--unselected-prefix=" ◻︎ " |
			sort
	)

	files_classify=$(
		echo "$files_available" |
			sort |
			gum filter \
				--header="[6/6] $action classify rasters..." \
				--indicator=">" \
				--no-fuzzy \
				--no-fuzzy-sort \
				--no-limit \
				--prompt="" \
				--selected="$(echo -n "$files_classify" | tr "\n" ",")" \
				--selected-prefix=" ◼︎ " \
				--unselected-prefix=" ◻︎ " |
			sort
	)

	if [ "$files_fit" = "" ] && [ "$files_classify" = "" ]; then
		echo "# ✘ No files selected for fit or classify, aborting." |
			gum format
		exit 1
	fi

	gum format -- \
		"# Workspace" "$workspace" \
		"# Centers file" "$centers_file" \
		"# Centroids" "$centroids" \
		"# Iterations" "$n_times" \
		"# Seed" "$seed" \
		"# fit rasters" "$files_fit" \
		"# classify rasters" "$files_classify" |
		gum pager

	typeset -p "${vars[@]}"

	if gum confirm "Save config to \"$config\"?" --negative="Cancel"; then
		typeset -p "${vars[@]}" >"$config"
		echo "# ✔︎ K-Means config saved to \"$config\"" |
			gum format
	else
		echo "# ✘ K-Means config aborted" |
			gum format
	fi
}

function subcommand_run {

	case "$#" in
		1)
			config="$1"
			if [ ! -f "$config" ]; then
				echo "Usage: kmeans run <config_file>"
				echo "# ✘ Config file \"$config\" not found, aborting." |
					gum format
				exit 1
			fi
			source "$config" && validate_config
			;;
		*)
			echo "Usage: kmeans run <config_file>"
			exit 1
			;;
	esac

	# gum format -- \
	# 	"# Workspace" "$workspace" \
	# 	"# Centers file" "$centers_file" \
	# 	"# Centroids" "$centroids" \
	# 	"# Iterations" "$n_times" \
	# 	"# Seed" "$seed" \
	# 	"# fit rasters" "$files_fit" \
	# 	"# classify rasters" "$files_classify" |
	# 	gum pager

	# fit
	echo "# Fitting K-Means model..." | gum format
	kmeans_fit_rasters

	# classify
	echo "# Classifying rasters..." | gum format
	kmeans_classify_rasters

	# average
	echo "# Generating mean raster..." | gum format
	kmeans_mean_raster

	# differences
	echo "# Generating difference rasters..." | gum format
	kmeans_difference_rasters

	echo "# K-Means processing complete!" | gum format

}

function kmeans_fit_rasters {
	if [ ! -f "$workspace/$centers_file" ]; then
		local inputs=()
		while IFS= read -r input; do
			inputs+=("$workspace/$input")
		done <<<"$files_fit"

		kmeans_fit \
			-i "${inputs[@]}" \
			-o "$workspace/$centers_file" \
			-t "$n_times" \
			-c "$centroids" \
			-r "$seed"
	fi
	echo "✔︎ $workspace/$centers_file" | gum format
}

function kmeans_classify_rasters {
	local output=""
	while IFS= read -r input; do
		output="${input%.tif}_classed.tif"
		kmeans_classify_single_raster "$workspace/$input" "$workspace/$output" "$workspace/$centers_file"
	done <<<"$files_classify"
}

function kmeans_classify_single_raster {
	# 1: input
	# 2: output
	# 3: centers_file
	local pngfile="${2%.tif}.png"
	[ ! -f "$2" ] && kmeans_classify -i "$1" -k "$3" -o "$2" 2>/dev/null
	[ ! -f "$pngfile" ] && plot -i "$2" -o "$pngfile"
	echo "✔︎ $2" | gum format
	return 0
}

function kmeans_mean_raster {
	local inputs=()
	local output="$workspace/${centers_file%.*}_mean.tif"
	local pngfile="${output%.tif}.png"
	while IFS= read -r input; do
		inputs+=("$workspace/$input")
	done <<<"$files_fit"

	if [ ! -f "$output" ]; then
		means -i "${inputs[@]}" -o "$output" 2>/dev/null
		if [ $? -ne 0 ]; then
			echo "# ✘ Failed to generate mean raster." |
				gum format
			return 1
		fi
	fi
	[ ! -f "$pngfile" ] && plot -i "$output" -o "$pngfile"
	echo "✔︎ $output" | gum format
	return 0
}

function kmeans_difference_rasters {
	local filename=""
	local date=""
	local output=""
	local pngfile=""
	while IFS= read -r input; do
		filename="$(basename "$input")"
		date="$(echo "$filename" | cut -c 1-8)"
		output="$workspace/${centers_file%.*}_mean_diff_${date}.tif"
		pngfile="${output%.tif}.png"
		if [ ! -f "$output" ]; then
			subtract \
				-i "$workspace/${centers_file%.*}_mean.tif" "$workspace/$input" \
				-o "$output" \
				2>/dev/null
		fi
		echo "✔︎ $output" | gum format
		[ ! -f "$pngfile" ] && plot -i "$output" -o "$pngfile"
	done <<<"$files_classify"
	return 0
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
	main "$@"
fi
